/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package defaultPackage

import org.acme.travel.taxfile;


rule "Determine Deductions" ruleflow-group "deductions"

when
    $mytax: taxfile(processed == false, income < 50000)
then
	System.out.println("Hello taxpayer " + $mytax);   
	$mytax.setProcessed( true );
    
end

rule "Don't process taxfile above 50k income" ruleflow-group "deductions"

when
    $mytax: taxfile(processed == false, income > 50000)
then
	System.out.println("This system can't process your income " + $mytax.getIncome() + " which is above 50k");
 	$mytax.setProcessed( false ); 
    
end
